server:
  port: 7007
  servlet:
    session:
      timeout: 1h
  compression:
    enabled: true
    min-response-size: 1024

sk:
  security:
    cors:
      allowed-origin-patterns:
        - http://localhost:4173
        - http://127.0.0.1:4173

file-storage:
  local:
    root-path: ./files
    # set the file path
    pathStrategy: byId
    dateFormat: yyyyMM/dd
    nameStrategy: seqAndOriginalName
custom-cache:
  entries:
    projectCache: 1d
    fileCache: 1h
    userCache: 1h
    deptCache: 1d
    projectPermissionCache: 1d
    commonCache: 30d
    oauthFlowCache: 10m
